version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/prana-club
hooks:
  BeforeInstall:
    - location: script/before_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300